/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardHitsRouteImport } from './routes/dashboard/hits'
import { Route as DashboardKellyRouteImport } from './routes/dashboard/kelly'
import { Route as DashboardPredictionsRouteImport } from './routes/dashboard/predictions'
import { Route as DashboardKellyTrackerIdRouteImport } from './routes/dashboard/kelly/$trackerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHitsRoute = DashboardHitsRouteImport.update({
  id: '/hits',
  path: '/hits',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKellyRoute = DashboardKellyRouteImport.update({
  id: '/kelly',
  path: '/kelly',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPredictionsRoute = DashboardPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKellyTrackerIdRoute = DashboardKellyTrackerIdRouteImport.update({
  id: '/$trackerId',
  path: '/$trackerId',
  getParentRoute: () => DashboardKellyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/hits': typeof DashboardHitsRoute
  '/dashboard/kelly': typeof DashboardKellyRouteWithChildren
  '/dashboard/predictions': typeof DashboardPredictionsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/kelly/$trackerId': typeof DashboardKellyTrackerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/hits': typeof DashboardHitsRoute
  '/dashboard/kelly': typeof DashboardKellyRouteWithChildren
  '/dashboard/predictions': typeof DashboardPredictionsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/kelly/$trackerId': typeof DashboardKellyTrackerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/hits': typeof DashboardHitsRoute
  '/dashboard/kelly': typeof DashboardKellyRouteWithChildren
  '/dashboard/predictions': typeof DashboardPredictionsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/kelly/$trackerId': typeof DashboardKellyTrackerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/hits'
    | '/dashboard/kelly'
    | '/dashboard/predictions'
    | '/dashboard/'
    | '/dashboard/kelly/$trackerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/hits'
    | '/dashboard/kelly'
    | '/dashboard/predictions'
    | '/dashboard'
    | '/dashboard/kelly/$trackerId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/hits'
    | '/dashboard/kelly'
    | '/dashboard/predictions'
    | '/dashboard/'
    | '/dashboard/kelly/$trackerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/hits': {
      id: '/dashboard/hits'
      path: '/hits'
      fullPath: '/dashboard/hits'
      preLoaderRoute: typeof DashboardHitsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kelly': {
      id: '/dashboard/kelly'
      path: '/kelly'
      fullPath: '/dashboard/kelly'
      preLoaderRoute: typeof DashboardKellyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/predictions': {
      id: '/dashboard/predictions'
      path: '/predictions'
      fullPath: '/dashboard/predictions'
      preLoaderRoute: typeof DashboardPredictionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kelly/$trackerId': {
      id: '/dashboard/kelly/$trackerId'
      path: '/$trackerId'
      fullPath: '/dashboard/kelly/$trackerId'
      preLoaderRoute: typeof DashboardKellyTrackerIdRouteImport
      parentRoute: typeof DashboardKellyRoute
    }
  }
}

interface DashboardKellyRouteChildren {
  DashboardKellyTrackerIdRoute: typeof DashboardKellyTrackerIdRoute
}

const DashboardKellyRouteChildren: DashboardKellyRouteChildren = {
  DashboardKellyTrackerIdRoute: DashboardKellyTrackerIdRoute,
}

const DashboardKellyRouteWithChildren = DashboardKellyRoute._addFileChildren(
  DashboardKellyRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardHitsRoute: typeof DashboardHitsRoute
  DashboardKellyRoute: typeof DashboardKellyRouteWithChildren
  DashboardPredictionsRoute: typeof DashboardPredictionsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardHitsRoute: DashboardHitsRoute,
  DashboardKellyRoute: DashboardKellyRouteWithChildren,
  DashboardPredictionsRoute: DashboardPredictionsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
